version: '3'

services:
  panel:
    container_name: panel
    restart: always
    build: .
    ports:
      - "5100:5100"
    command: panel serve --show apps/hatch.py --allow-websocket-origin=* --port=5100 

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - panel
