version: '3'

services:
  panel:
    container_name: panel
    restart: always
    build: .
    ports:
      - "80:80"
    command: panel serve apps/hatch.py apps/test-hatch.py --port=80 --allow-websocket-origin=params.tecommons.org --allow-websocket-origin=95.111.227.14
